apiVersion: v1
kind: Service
metadata:
  name: prospectf500-app1-backend
  labels:
    app: prospectf500-app1-backend
    tenant: opsera-se
    app-identifier: prospectf500-app1
    environment: dev
    managed-by: opsera-gitops
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: prospectf500-app1-backend
