apiVersion: v1
kind: Service
metadata:
  name: prospectf500-app1-frontend
  labels:
    app: prospectf500-app1-frontend
    tenant: opsera-se
    app-identifier: prospectf500-app1
    environment: dev
    managed-by: opsera-gitops
  annotations:
    # ExternalDNS will create this DNS record automatically
    external-dns.alpha.kubernetes.io/hostname: prospectf500-app1-dev.agents.opsera-labs.com
    # For NLB (required for internet-facing)
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    # Learning #135: HTTPS with ACM Certificate
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:eu-north-1:ACCOUNT_ID:certificate/CERT_ID
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
spec:
  type: LoadBalancer
  selector:
    app: prospectf500-app1-frontend
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
    - name: https
      port: 443
      targetPort: 8080
      protocol: TCP
